CREATE TABLE `db`.`server_inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fqdn` VARCHAR(45) NOT NULL,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `features` VARCHAR(90) NULL,
  `ipaddr` VARCHAR(15) NOT NULL,
  `label` VARCHAR(45) NULL,
  `groups` VARCHAR(45) NULL,
  `upd` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));
